### ISSUE TITLE
Suggestion: Code Style Check GitHub Action

### ISSUE THREAD

**Issue by degenone** [FritzAndFriends/TagzApp#131]
After the Tabs vs Spaces and `.editorconfig` talk on stream I decided to experiment with creating a GitHub Action for code style checking.

Here is what I came up with:

```yml
name: code-style-check
on: pull_request

jobs:

  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      cs_files: ${{ steps.cs.outputs.cs_files }}
      js_css_files: ${{ steps.js_css.outputs.js_css_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get diff
        run: |
          {
            echo 'diff<<EOF'
            git diff main --name-status
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Assign C# files to output
        id: cs
        run: |
          {
            echo 'cs_files<<EOF'
            echo "$diff" | grep -E "^[ACMR][0-9]{0,3}[[:space:]]+.+\.cs$" | sed -E "s/.*[[:space:]]+//"
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Assign JS/CSS files to output
        id: js_css
        run: |
          {
            echo 'js_css_files<<EOF'
            echo "$diff" | grep -E "^[ACMR][0-9]{0,3}[[:space:]]+.+\.(js|css)$" | sed -E "s/.*[[:space:]]+//"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  run-dotnet-format:
    if: needs.get-changed-files.outputs.cs_files != ''
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: dotnet format
        run: dotnet format --verbosity detailed --verify-no-changes --include ${{ needs.get-changed-files.outputs.cs_files }}

  run-prettier:
    if: needs.get-changed-files.outputs.js_css_files != ''
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ${{ needs.get-changed-files.outputs.js_css_files }}
          dry: true
```

This will only check the files the PR changed. If we assume that the current files are formatted properly ( #121 ), it would only check the new code in the PR. 

It also includes a job with `Prettier` for `.css` and `.js` checks but this could be dropped.

I'm not sure what would be the best approach with `.cshtml` files.

My version does not actually format the files but it is there to encourage contributors to run `dotnet format` (and maybe `npx prettier`) before their PR.
