### ISSUE TITLE
.NET Conf prep - Add the .NET Conf header to the waterfall view

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/TagzApp#282]
![image](https://github.com/FritzAndFriends/TagzApp/assets/78577/18930a0d-0369-4ff1-84d9-8c5e453a6f0e)

**Comment by csharpfritz** [comment]
Let's look at using a left and right image:

![image](https://github.com/FritzAndFriends/TagzApp/assets/78577/0c8b6670-64e7-4d0e-be09-8eb29fb3d1ac)

![image](https://github.com/FritzAndFriends/TagzApp/assets/78577/d906b3d7-29f7-4e94-95ec-2dc15021a078)

**Comment by csharpfritz** [comment]
Solved this with some CSS:  

```css
.waterfallHeader { height: 90px; background-color: #190649; position: relative; }
u { display: block; position: absolute; left: 0px; top: 0px;  background-image: url('https://user-images.githubusercontent.com/78577/280840339-18930a0d-0369-4ff1-84d9-8c5e453a6f0e.png'); height: 90px; width: 250px; }
img { position: absolute; right: 0; top: 0; z-index: 0; clip-path: polygon(50% 0 , 100% 0, 100% 100%, 50% 100%); }
h4 { text-align: center; z-index: 3; position: absolute; left: calc(50vw - 14em); bottom: 0;}
```

and some markdown:

```markdown
<u></u>  ![](https://user-images.githubusercontent.com/78577/280840339-18930a0d-0369-4ff1-84d9-8c5e453a6f0e.png)

#### **Use hashtag #dotnetconf on Twitter or Mastodon**
```
